global:
  marketplace-ami: false
  owner: jorge@aviatrix.com
  qsname: avx-awsmp-nextgentransithub
  regions:
    - us-east-1
  reporting: true
tests:
  quickstart-aviatrix-master:
    parameter_input: avx-awsmp-nextgentransithub-master-params.json
    template_file: avx-awsmp-nextgentransithub-master.template
